// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:erni_mobile/reflection.dart' as prefix0;
import 'package:erni_mobile/ui/view_models/main/dashboard_view_model.dart'
    as prefix1;
import 'package:injectable/src/injectable_annotations.dart' as prefix2;
import 'package:meta/meta.dart' as prefix3;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'DashboardViewModel',
            r'.DashboardViewModel',
            134217735,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 3, 10, 11],
            const <int>[
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              3,
              22,
              4,
              5,
              6,
              7,
              8,
              9,
              10
            ],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => (menuProvider, _logger) =>
                  b ? prefix1.DashboardViewModel(menuProvider, _logger) : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[prefix2.injectable, prefix0.reflectable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'menus', 151127045, 0, const prefix0.Reflector(),
            -1, -1, -1, null, const []),
        r.VariableMirrorImpl(r'selectedMenu', 151127045, 0,
            const prefix0.Reflector(), -1, -1, -1, null, const []),
        r.VariableMirrorImpl(
            r'messageFromSplash',
            67239941,
            0,
            const prefix0.Reflector(),
            -1,
            -1,
            -1,
            null,
            const <Object>[prefix1.messageParam]),
        r.MethodMirrorImpl(r'onInitialize', 35651586, 0, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 4),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 5),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 6),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 1, 7),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 2, 8),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 2, 9),
        r.MethodMirrorImpl(r'selectedMenuIndex', 2097155, 0, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'', 0, 0, -1, -1, -1, null, const <int>[0, 1],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, -1, -1, null, const <int>[5],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1, null,
            const <int>[6], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(
            r'addListener',
            1310722,
            -1,
            -1,
            -1,
            -1,
            null,
            const <int>[7],
            const prefix0.Reflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'removeListener',
            1310722,
            -1,
            -1,
            -1,
            -1,
            null,
            const <int>[8],
            const prefix0.Reflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'dispose',
            1310722,
            -1,
            -1,
            -1,
            -1,
            null,
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[prefix3.mustCallSuper]),
        r.MethodMirrorImpl(
            r'notifyListeners',
            1310722,
            -1,
            -1,
            -1,
            -1,
            null,
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[
              prefix3.protected,
              prefix3.visibleForTesting,
              const pragma('vm:notify-debugger-on-exception')
            ]),
        r.MethodMirrorImpl(
            r'hasListeners',
            2097155,
            -1,
            -1,
            -1,
            -1,
            null,
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[prefix3.protected]),
        r.MethodMirrorImpl(r'onFirstRender', 35651586, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'menuProvider', 134348806, 11,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'_logger', 134349862, 11,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'_menus', 151126118, 5,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'_selectedMenu', 151126118, 7,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'_messageFromSplash', 67240038, 9,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'other', 134348806, 12,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'invocation', 134348806, 14,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'listener', 134217734, 17,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'listener', 134217734, 18,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null)
      ],
      <Type>[prefix1.DashboardViewModel],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'addListener': (dynamic instance) => instance.addListener,
        r'removeListener': (dynamic instance) => instance.removeListener,
        r'dispose': (dynamic instance) => instance.dispose,
        r'notifyListeners': (dynamic instance) => instance.notifyListeners,
        r'hasListeners': (dynamic instance) => instance.hasListeners,
        r'onInitialize': (dynamic instance) => instance.onInitialize,
        r'onFirstRender': (dynamic instance) => instance.onFirstRender,
        r'menus': (dynamic instance) => instance.menus,
        r'selectedMenu': (dynamic instance) => instance.selectedMenu,
        r'messageFromSplash': (dynamic instance) => instance.messageFromSplash,
        r'selectedMenuIndex': (dynamic instance) => instance.selectedMenuIndex
      },
      {
        r'menus=': (dynamic instance, value) => instance.menus = value,
        r'selectedMenu=': (dynamic instance, value) =>
            instance.selectedMenu = value,
        r'messageFromSplash=': (dynamic instance, value) =>
            instance.messageFromSplash = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
