name: Run pub get and code generation
description: Gets pub packages and runs build_runner for code generation

inputs:
  generate_intl:
    description: 'Whether to run generation of localization files'
    default: 'false'
  working_directory:
    description: 'The working directory'
    required: true

runs:
  using: composite
  steps:
    - run: dart pub get
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - run: dart pub global activate intl_utils
      shell: bash
      if: ${{ inputs.generate_intl == 'true' }}

    - run: dart pub global run intl_utils:generate
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      if: ${{ inputs.generate_intl == 'true' }}

    - run: dart run build_runner build --delete-conflicting-outputs
      shell: bash
      working-directory: ${{ inputs.working_directory }}