name: Install Flutter
description: Installs the latest Flutter SDK

runs:
  using: 'composite'
  steps:
    - uses: subosito/flutter-action@v2.6.2
      with:
        channel: 'stable'

    - run: flutter --version
      shell: bash