name: Run Tests
description: Run tests for the project

inputs:
  working_directory:
    description: 'The working directory'
    required: true

runs:
  using: composite
  steps:
    - name: Ensure full coverage
      shell: bash
      run: |
        fvm dart run full_coverage
      working-directory: ${{ inputs.working_directory }}

    - name: Run tests
      shell: bash
      run: |
        fvm flutter test --coverage
      working-directory: ${{ inputs.working_directory }}