parameters:
  - name: TargetEnvironment
    type: string
    default: dev

variables:
  - group: AppleSigning-${{ parameters.TargetEnvironment }}
  - template: azure-pipelines-ci-variables.yml
    parameters:
      TargetEnvironment: ${{ parameters.TargetEnvironment }}

steps:
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: $(DistributionCertificateFile)
      certPwd: "$(DistributionCertificatePassword)"
      keychain: "temp"

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: "secureFiles"
      provProfileSecureFile: $(DistributionProvisioningProfile)

  - template: steps/download-secrets-file.yml

  - template: steps/download-fastlane-env-files.yml

  - template: steps/install-flutter.yml

  - template: steps/run-pub-get-and-build-runner.yml
    parameters:
      WorkingDirectory: $(CoreProjectDirectory)
      RunIntlGeneration: false

  - template: steps/run-pub-get-and-build-runner.yml
    parameters:
      WorkingDirectory: $(WorkingDirectory)
      RunIntlGeneration: true

  - script: |
      bash ../scripts/gen_export_options_plist.sh $(APP_ENVIRONMENT)
      cat ios/Runner/ExportOptions.plist
    displayName: Generate Export Options Plist
    workingDirectory: $(WorkingDirectory)

  - script: fastlane build_ios_release_appcenter
    displayName: Build iOS
    workingDirectory: $(WorkingDirectory)

  - task: ArchiveFiles@2
    displayName: Zip dSYM
    inputs:
      rootFolderOrFile: "$(WorkingDirectory)/build/ios/archive/Runner.xcarchive/dSYMs/Runner.app.dSYM"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/Runner.app.dSYM.zip"
      replaceExistingArchive: true

  - template: steps/publish-artifacts.yml
    parameters:
      Artifacts: |
        **/ipa/*.ipa
