parameters:
  - name: TargetEnvironment
    type: string
    default: dev

variables:
  - group: AndroidSigning
  - template: azure-pipelines-ci-variables.yml
    parameters:
      TargetEnvironment: ${{ parameters.TargetEnvironment }}

steps:
  - task: DownloadSecureFile@1
    name: KeystoreFile
    displayName: Download keystore file
    inputs:
      secureFile: $(KeystoreFile)

  - task: DownloadSecureFile@1
    name: KeystorePropertiesFile
    displayName: Download keystore properties file
    inputs:
      secureFile: $(KeystorePropertiesFile)

  - task: CopyFiles@2
    displayName: Copy keystore files
    inputs:
      SourceFolder: "$(Agent.TempDirectory)"
      Contents: |
        $(KeystoreFile)
        $(KeystorePropertiesFile)
      TargetFolder: "$(WorkingDirectory)/android/app"

  - task: JavaToolInstaller@0
    displayName: Set Java version
    inputs:
      versionSpec: "11"
      jdkArchitectureOption: "x64"
      jdkSourceOption: "PreInstalled"

  - template: steps/download-secrets-file.yml

  - template: steps/download-fastlane-env-files.yml

  - template: steps/install-flutter.yml

  - template: steps/run-pub-get-and-build-runner.yml

  - script: fastlane build_android_release_appcenter output:apk
    displayName: Build Android
    workingDirectory: $(WorkingDirectory)

  - template: steps/publish-artifacts.yml
    parameters:
      Artifacts: |
        **/app-release.apk
