parameters:
  - name: TargetEnvironment
    type: string
    default: dev

variables:
  - template: azure-pipelines-ci-variables.yml
    parameters:
      TargetEnvironment: ${{ parameters.TargetEnvironment }}

steps:
  - template: steps/download-secrets-file.yml

  - template: steps/install-flutter.yml

  - template: steps/run-pub-get-and-build-runner.yml
    parameters:
      WorkingDirectory: $(CoreProjectDirectory)
      RunIntlGeneration: false

  - template: steps/run-pub-get-and-build-runner.yml
    parameters:
      WorkingDirectory: $(WorkingDirectory)
      RunIntlGeneration: true

  - template: steps/set-secrets-as-dart-define-params.yml

  - script: flutter build web $(SecretsDartDefines)
    displayName: Build Web
    workingDirectory: $(WorkingDirectory)

  - task: ArchiveFiles@2
    displayName: Zip build output as build artifact
    inputs:
      rootFolderOrFile: "$(WorkingDirectory)/build/web"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/app-web.zip"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: Publish build artifact
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
