parameters:
  - name: TargetEnvironment
    type: string
    default: dev

variables:
  - group: WindowsSigning
  - template: azure-pipelines-ci-variables.yml
    parameters:
      TargetEnvironment: ${{ parameters.TargetEnvironment }}

steps:
  - template: steps/download-secrets-file.yml

  - template: steps/set-secrets-as-dart-define-params.yml

  - template: steps/install-flutter.yml

  - template: steps/run-pub-get-and-build-runner.yml
    parameters:
      WorkingDirectory: $(CoreProjectDirectory)
      RunIntlGeneration: false

  - template: steps/run-pub-get-and-build-runner.yml
    parameters:
      WorkingDirectory: $(WorkingDirectory)
      RunIntlGeneration: true

  - task: DownloadSecureFile@1
    displayName: Download secrets file
    inputs:
      secureFile: $(DistributionCertificateFile)

  - template: steps/run-command-with-secrets-as-json.yml
    parameters:
      Command: |
        flutter build windows $(SecretsDartDefines)
        echo y | flutter pub run msix:create --build-windows false --display-name $SecretsJson.AppName --publisher-display-name $(PublisherDisplayName) --identity-name "$($SecretsJson.AppId)$($SecretsJson.AppIdSuffix)" --certificate-path "$(Agent.TempDirectory)/$(DistributionCertificateFile)" --certificate-password "$(DistributionCertificatePassword)"

  - template: steps/publish-artifacts.yml
    parameters:
      Artifacts: |
        **/**/*.msix
