parameters:
  - name: TargetEnvironment
    displayName: Target Environment
    type: string
    default: dev
    values:
      - dev

trigger:
  - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: macos-latest

extends:
  template: templates/azure-pipelines-ci-ios-template.yml
  parameters:
    TargetEnvironment: ${{ parameters.TargetEnvironment }}
