// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:meta/meta.dart' as prefix1;
import 'package:test_app/view_model.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'BViewModel',
            r'.BViewModel',
            134217735,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 3, 4, 11],
            const <int>[
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10
            ],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix0.BViewModel() : null},
            -1,
            -1,
            const <int>[-1],
            const <Object>[prefix0.reflector],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'name', 67240965, 0, const prefix0.Reflector(),
            -1, -1, -1, null, const <Object>[prefix0.nameParam]),
        r.VariableMirrorImpl(r'id', 67240965, 0, const prefix0.Reflector(), -1,
            -1, -1, null, const <Object>[prefix0.idParam]),
        r.VariableMirrorImpl(r'other', 134349829, 0, const prefix0.Reflector(),
            -1, -1, -1, null, const <Object>[prefix0.otherParam]),
        r.MethodMirrorImpl(
            r'onInitialize',
            35651586,
            0,
            -1,
            -1,
            -1,
            null,
            const <int>[0],
            const prefix0.Reflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(r'goBack', 35651586, 0, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 5),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 6),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 7),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 1, 8),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 2, 9),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 2, 10),
        r.MethodMirrorImpl(r'', 64, 0, -1, -1, -1, null, const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, -1, -1, null, const <int>[4],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1, null,
            const <int>[5], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(
            r'addListener',
            1310722,
            -1,
            -1,
            -1,
            -1,
            null,
            const <int>[6],
            const prefix0.Reflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'removeListener',
            1310722,
            -1,
            -1,
            -1,
            -1,
            null,
            const <int>[7],
            const prefix0.Reflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'dispose',
            1310722,
            -1,
            -1,
            -1,
            -1,
            null,
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[prefix1.mustCallSuper]),
        r.MethodMirrorImpl(
            r'notifyListeners',
            1310722,
            -1,
            -1,
            -1,
            -1,
            null,
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[
              prefix1.protected,
              prefix1.visibleForTesting,
              const pragma('vm:notify-debugger-on-exception')
            ]),
        r.MethodMirrorImpl(
            r'hasListeners',
            2097155,
            -1,
            -1,
            -1,
            -1,
            null,
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[prefix1.protected])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'parameters',
            67252230,
            3,
            const prefix0.Reflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            #parameters),
        r.ParameterMirrorImpl(r'_name', 67240038, 6, const prefix0.Reflector(),
            -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'_id', 67240038, 8, const prefix0.Reflector(),
            -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'_other', 134348902, 10,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'other', 134348806, 12,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'invocation', 134348806, 14,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'listener', 134217734, 17,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'listener', 134217734, 18,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null)
      ],
      <Type>[prefix0.BViewModel],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'addListener': (dynamic instance) => instance.addListener,
        r'removeListener': (dynamic instance) => instance.removeListener,
        r'dispose': (dynamic instance) => instance.dispose,
        r'notifyListeners': (dynamic instance) => instance.notifyListeners,
        r'hasListeners': (dynamic instance) => instance.hasListeners,
        r'onInitialize': (dynamic instance) => instance.onInitialize,
        r'goBack': (dynamic instance) => instance.goBack,
        r'name': (dynamic instance) => instance.name,
        r'id': (dynamic instance) => instance.id,
        r'other': (dynamic instance) => instance.other
      },
      {
        r'name=': (dynamic instance, value) => instance.name = value,
        r'id=': (dynamic instance, value) => instance.id = value,
        r'other=': (dynamic instance, value) => instance.other = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
