name: Run command with secrets as JSON
description: Runs a command with secrets as JSON

inputs:
  app_environment:
    description: 'The app environment'
    required: true
  working_directory:
    description: 'The working directory'
    required: true
  command:
    description: 'The command to run'
    required: true

runs:
  using: composite
  steps:
    - run: |
        $SecretsJson = Get-Content ".environment/${{ inputs.app_environment }}.json" | Out-String | ConvertFrom-Json
        ${{ inputs.command }}
      shell: powershell
      working-directory: ${{ inputs.working_directory }}