name: Install Flutter
description: Installs the specific Flutter SDK version configured in the project

inputs:
  working_directory:
    description: 'The working directory'
    required: true

runs:
  using: composite
  steps:
    - run: |
        brew install fvm
        fvm install
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - run: |
        touch $HOME/.temprc
        echo "alias flutter='fvm flutter'" >> $HOME/.temprc
        echo "alias dart='fvm dart'" >> $HOME/.temprc
        source $HOME/.temprc
      shell: bash

    - run: flutter --version
      shell: bash