name: Install Flutter
description: Installs the specific Flutter SDK version configured in the project

inputs:
  working_directory:
    description: 'The working directory'
    required: true

runs:
  using: composite
  steps:
    - run: curl -fsSL https://fvm.app/install.sh | bash
      shell: bash

    - run: fvm install
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - run: fvm flutter doctor -v
      shell: bash
      working-directory: ${{ inputs.working_directory }}