name: Install Flutter
description: Installs the latest Flutter SDK

runs:
  using: composite
  steps:
    - uses: subosito/flutter-action@v2.6.2
      with:
        flutter-version: '3.10.5'
        channel: 'stable'

    - run: flutter --version
      shell: bash