name: Install Flutter
description: Installs the specific Flutter SDK version configured in the project

inputs:
  working_directory:
    description: 'The working directory'
    required: true

runs:
  using: composite
  steps:
    - uses: kuhnroyal/flutter-fvm-config-action@v1
      with:
        path: ${{ inputs.working_directory }}/.fvm/fvm_config.json

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}

    - run: flutter --version
      shell: bash