name: Set secrets as Dart define params
description: Sets the secret file values as Dart define params

inputs:
  app_environment:
    description: 'The app environment'
    required: true
  working_directory:
    description: 'The working directory'
    required: true

runs:
  using: composite
  steps:
    - run: |
        $dartDefineParams = ./../scripts/set_secrets_as_dart_define_params.ps1 ${{ inputs.app_environment }}
        echo "DART_DEFINE_PARAMS=$dartDefineParams" >> $GITHUB_ENV
      shell: powershell
      working-directory: ${{ inputs.working_directory }}