name: Runs DCM code analysis
description: Runs Dart Code Metrics code analysis and checks for the project

inputs:
  working_directory:
    description: "The working directory"
    required: true
  github_token:
    description: "The GitHub token"
    required: true
  dcm_ci_key:
    description: "The DCM CI key"
    required: true
  dcm_ci_email:
    description: "The DCM CI email"
    required: true

runs:
  using: composite
  steps:
    - name: Install DCM
      uses: CQLabs/setup-dcm@276868e2e47402b2a14a252afa353602d41f06ae # v1
      with:
        github_token: ${{ inputs.github_token }}

    - name: Run DCM code analysis
      uses: CQLabs/dcm-action@b55273ad11b1f7f9e5714e774572f4e846300288 # v1.0.1
      with:
        github_token: ${{ inputs.github_token }}
        ci_key: ${{ inputs.dcm_ci_key }}
        email: ${{ inputs.dcm_ci_email }}
        folders: ${{ inputs.working_directory }}/lib

    - name: Run DCM code checks
      run: |
        # Running checks for unnecessary nullable parameters
        dcm check-unnecessary-nullable lib --ci-key ${{ inputs.dcm_ci_key }} --email ${{ inputs.dcm_ci_email }}

        # Running checks for unused files
        # Add `--fatal-unused` if you want to fail this step if there are unused files
        dcm check-unused-files lib --ci-key ${{ inputs.dcm_ci_key }} --email ${{ inputs.dcm_ci_email }} --no-fatal-unused

        # Running checks for unused code
        # Add `--fatal-unused` if you want to fail this step if there are unused code
        dcm check-unused-code lib --ci-key ${{ inputs.dcm_ci_key }} --email ${{ inputs.dcm_ci_email }} --no-fatal-unused

        # Running checks for unused localizations
        dcm check-unused-l10n lib --ci-key ${{ inputs.dcm_ci_key }} --email ${{ inputs.dcm_ci_email }}
      working-directory: ${{ inputs.working_directory }}
      shell: bash