name: erni_mobile_core
description: Core features of ERNI mobile blueprint
version: 0.0.0

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  app_links: ^3.2.0
  connectivity_plus: ^2.3.2
  drift: ^1.7.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.5.0
  meta: ^1.7.0
  package_info_plus: ^1.4.3
  page_transition: ^2.0.5
  path: ^1.8.1
  path_provider: ^2.0.11
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  sqlite3: ^1.7.1
  sqlite3_flutter_libs: ^0.5.7
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.15.2
  erni_mobile_lints:
    path: ../erni_mobile_lints
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
