name: erni_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.0+0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.3
  dio: ^4.0.6
  drift: ^1.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  get_it: ^7.2.0
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.5.0
  jwt_decoder: ^2.0.1
  meta: ^1.3.0
  package_info_plus: ^1.4.3+1
  page_transition: ^2.0.9
  path: ^1.8.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  responsive_framework: ^0.2.0
  retrofit: ^3.0.1
  sentry: ^6.8.0
  sentry_flutter: ^6.8.0
  shared_preferences: ^2.0.15
  smartstruct: ^1.2.4+1
  sqlite3: ^1.8.0
  uuid: ^3.0.5
  validation_notifier: ^1.4.5

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.17.1
  drift_dev: ^1.6.0
  flutter_gen_runner: ^4.1.6
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  mockito: ^5.2.0
  msix: ^3.6.2
  retrofit_generator: ^4.0.1
  smartstruct_generator: ^1.2.6

dependency_overrides: 
  analyzer: ^4.6.0

flutter_gen:
  output: lib/ui/resources
  line_length: 120
  fonts:
    enabled: false

# If you want to support adaptive icons on Android, follow the instructions at https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/graphics/ic_launcher.png"
  web:
    generate: true
    image_path: "assets/graphics/ic_launcher.png"
    background_color: "#033778"
    theme_color: "#033778"
  windows:
    generate: true
    image_path: "assets/graphics/ic_launcher.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/graphics/

  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  class_name: Il8n
  arb_dir: lib/common/localization
  output_dir: lib/common/localization/generated

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#033778"
  #background_image: "assets/background.png"
  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.
  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/graphics/ic_launcher.png

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. Currently, it is only supported for Android < v12 and iOS.
  #branding: assets/dart.png
  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom
  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png
  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # The image parameter sets the splash screen icon image. If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    # image: assets/graphics/ic_erni_logo.png
    # App icon background color.
    icon_background_color: "#033778"

    # The image_dark parameter and icon_background_color_dark set the image and icon background
    # color when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    #image_dark: assets/android12splash-invert.png
    icon_background_color_dark: "#033778"
  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false
  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center
  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true
  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

msix_config:
  msix_version: 1.0.0.0
  logo_path: assets/graphics/ic_launcher.png
  capabilities: internetClient