name: Set app environment and secrets
description: Sets the current app environment and secrets file

inputs:
  target_environment:
    description: 'The target environment'
    default: dev
  working_directory:
    description: 'The working directory'
    required: true

runs:
  using: composite
  steps:
    - run: |
        APP_ENVIRONMENT_VALUE=${{ inputs.target_environment }}
        echo "APP_ENVIRONMENT=$APP_ENVIRONMENT_VALUE" >> $GITHUB_ENV
        echo "SECRETS_FILE_KEY=${APP_ENVIRONMENT_VALUE}_secrets" >> $GITHUB_ENV
      shell: bash
    
    - run: |
        rm -d -R .secrets
        mkdir .secrets
        echo -n "${{ secrets[env.SECRETS_FILE_KEY] }}" | base64 --decode > .secrets/${{ env.APP_ENVIRONMENT  }}.secrets
      shell: bash
      working-directory: ${{ inputs.working_directory }}