name: Code Analysis

on:
  push:
    paths:
      - .github/**/*.yml
      - scripts/**
      - starterkit_app/**
    branches:
      - main

  pull_request:
    paths:
      - .github/**/*.yml
      - scripts/**
      - starterkit_app/**
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PROJECT_WORKING_DIRECTORY: "starterkit_app"

permissions: {}

jobs:
  run-code-analysis:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Install Flutter
        uses: ./.github/workflows/steps/install-flutter
        with:
          working_directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Check formatting
        run: dart format --line-length=120 --set-exit-if-changed .
        working-directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Check for duplicate lines of code
        run: |
          npm install -g jscpd
          npx jscpd lib --reporters consoleFull --threshold 5
        working-directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Run code generation
        uses: ./.github/workflows/steps/run-pub-get-and-code-generation
        with:
          generate_intl: "true"
          working_directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Run Dart code analysis
        run: |
          dart analyze .
        working-directory: ${{ env.PROJECT_WORKING_DIRECTORY }}
