name: Code Validation

on:
  workflow_call:
    inputs:
      target_environment:
        type: string
        required: false
        default: 'dev'

  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/templates/steps/install-flutter
