name: Code Validation

on:
  workflow_call:
    inputs:
      target_environment:
        type: string
        required: false
        default: 'dev'

  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

env:
  PROJECT_WORKING_DIRECTORY: 'erni_mobile'
  CORE_PROJECT_WORKING_DIRECTORY: 'erni_mobile_core'

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/templates/steps/install-flutter

      - name: Install JSCPD
        run: npm install -g jscpd

      - name: Install junitreport
        run: flutter pub global activate junitreport

      - name: Check formatting
        run: flutter format --line-length=120 --dry-run --set-exit-if-changed .
        working-directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Check for duplicate lines of code
        run: npx jscpd lib --reporters html --threshold 5
        working-directory: ${{ env.PROJECT_WORKING_DIRECTORY }}
      
