name: iOS Build

on:
  workflow_dispatch:
    inputs:
      target_environment:
        required: false
        type: choice
        description: Select environment
        default: dev
        options:
          - dev

  push:
    paths:
      - .github/**/*.yml
      - scripts/**
      - starterkit_app/**
    branches:
      - main

  pull_request:
    paths:
      - .github/**/*.yml
      - scripts/**
      - starterkit_app/**
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PROJECT_WORKING_DIRECTORY: "starterkit_app"

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set app environment
        uses: ./.github/workflows/steps/set-app-environment
        with:
          target_environment: ${{ github.event.inputs.target_environment }}

      # Uncomment this step if you already added your secrets file in your repository's secrets
      # - name: Set secrets file
      #   uses: ./.github/workflows/steps/set-secrets-file
      #   with:
      #     secrets_file_value: ${{ secrets[env.SECRETS_FILE_KEY] }}
      #     app_environment: ${{ env.APP_ENVIRONMENT }}
      #     working_directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Install Flutter
        uses: ./.github/workflows/steps/install-flutter
        with:
          working_directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Run code generation
        uses: ./.github/workflows/steps/run-pub-get-and-code-generation
        with:
          generate_intl: "true"
          working_directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Build iOS App
        run: |
          fastlane build_ios_release
        working-directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      # Enable this if you want to publish the IPA file as an artifact
      # - name: Publish iOS App
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ios_build
      #     path: ${{ env.PROJECT_WORKING_DIRECTORY }}/build/ios/ipa/**
