name: iOS Build

on:
  workflow_dispatch:
    inputs:
      target_environment:
        required: false
        type: choice
        description: Select environment
        default: dev
        options:
          - dev

  push:
    paths:
      - .github/**/*.yml
      - scripts/**
      - starterkit_app/**
    branches:
      - main

  pull_request:
    paths:
      - .github/**/*.yml
      - scripts/**
      - starterkit_app/**
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PROJECT_WORKING_DIRECTORY: "starterkit_app"

permissions: {}

jobs:
  build-ios:
    runs-on: macos-latest
    permissions: {}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: ruby/setup-ruby@6615b4b8a02c78c4d711c06df4b8a20aa685a45d # v1
        with:
          ruby-version: 2.7

      - run: bundle install
        working-directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Set app environment
        uses: ./.github/workflows/steps/set-app-environment
        with:
          target_environment: ${{ github.event.inputs.target_environment }}

      - name: Set secrets file
        uses: ./.github/workflows/steps/set-secrets-file
        with:
          secrets_file_value: ${{ secrets[env.SECRETS_FILE_KEY] }}
          app_environment: ${{ env.APP_ENVIRONMENT }}
          working_directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Install Flutter
        uses: ./.github/workflows/steps/install-flutter
        with:
          working_directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Run code generation
        uses: ./.github/workflows/steps/run-pub-get-and-code-generation
        with:
          generate_intl: "true"
          working_directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Build iOS App
        run: |
          bundle exec fastlane build_ios_release
        working-directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      # Enable this if you want to publish the IPA file as an artifact
      # - name: Publish iOS App
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ios_build
      #     path: ${{ env.PROJECT_WORKING_DIRECTORY }}/build/ios/ipa/**
