name: iOS Build

on:
  workflow_dispatch:
    inputs:
      target_environment:
        required: false
        type: choice
        description: Select environment
        default: dev
        options:
        - dev

  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]
      
concurrency: 
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PROJECT_WORKING_DIRECTORY: "erni_mobile"

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set app environment
        uses: ./.github/workflows/steps/set-app-environment
        with:
          target_environment: ${{ github.event.inputs.target_environment }}
      
      - name: Set secrets file
        uses: ./.github/workflows/steps/set-secrets-file
        with:
          secrets_file_value: ${{ secrets[env.SECRETS_FILE_KEY] }}
          app_environment: ${{ env.APP_ENVIRONMENT }}
          working_directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Install iOS distribution certificate
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_FILE }}
          p12-password: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_PASSWORD }}

      - name: Install iOS provisioning profile
        uses: akiojin/install-provisioning-profile-github-action@v1.0
        with:
          base64: ${{ secrets.IOS_PROVISIONING_PROFILE_FILE }}

      - name: Install Flutter
        uses: ./.github/workflows/steps/install-flutter

      - name: Run code generation
        uses: ./.github/workflows/steps/run-pub-get-and-code-generation
        with:
          generate_intl: "true"
          working_directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Build iOS App
        run: |
          fastlane build_ios_release
        working-directory: ${{ env.PROJECT_WORKING_DIRECTORY }}

      - name: Publish iOS App
        uses: actions/upload-artifact@v3
        with:
          name: ios_build
          path: ${{ env.PROJECT_WORKING_DIRECTORY }}/build/ios/ipa/**