targets:
  $default:
    builders:

      reflectable:
        generate_for:
          include:
            - lib/main.dart
        options:
          formatted: true
          terse_output: true
          auto_apply: false
          link_to_reflectable: true
          entry_points:
            - lib/main.dart

      injectable_generator|injectable_config_builder:
        enabled: true
        generate_for:
          include:
            - lib/core/dependency_injection.dart

      retrofit_generator|retrofit_config_builder:
        enabled: true
        generate_for:
          include:
            - lib/features/**/*_api.dart
